name: capstone
description: 'FFI bindings for the Capstone disassembler framework.'
version: 0.2.0
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  ffi: ^2.1.0

dev_dependencies:
  ffigen: ^11.0.0
  lints: ^3.0.0

ffigen:
  name: Capstone
  description: 'Bindings to Capstone'
  language: c
  output: 'lib/src/generated_bindings.dart'
  headers:
    entry-points:
      - thirdparty/capstone/include/capstone/capstone.h
    include-directives:
      - thirdparty/capstone/include/**
  functions:
    rename:
      'cs_(.*)': '$1'
  enums:
    member-rename:
      'cs_mode':
        'CS_MODE_([0-9])(.*)': '$$1$2'
        'CS_MODE_(.*)': '$1'
      'cs_opt_type':
        'CS_OPT_(.*)': '$1'
      'cs_opt_value':
        'CS_OPT_(.*)': '$1'
      'cs_op_type':
        'CS_OP_(.*)': '$1'
      'cs_ac_type':
        'CS_AC_(.*)': '$1'
      'cs_group_type':
        'CS_GRP_(.*)': '$1'
      'cs_err':
        'CS_ERR_(.*)': '$1'
      'cs_arch':
        'CS_ARCH_(.*)': '$1'
